### ISSUE TITLE
Slack bot for submitting answers and checking puzzle status

### ISSUE THREAD

**Issue by erwa** [cardinalitypuzzles/smallboard#11]
A Slack bot for submitting answers and checking puzzle status would be useful. One caveat: someone probably still needs to submit the answer on the actual hunt website, the Slack bot submission would only add the answer submission to the Small Board site. One of the jobs of the phone person besides verifying answers could be to ensure the "submitted answers" are actually submitted on the hunt website.

**Comment by asdfryan** [comment]
If I remember correctly, there's no real way to "submit the answer" on a website right? It was all via phone calls?

If this is the case, then what should happen is:
1) Someone types !answer XXX in the appropriate slack channel.
2) XXX for the corresponding puzzle is added to the answer queue.
3) Phone-person verifies the answer and marks it as correct/incorrect.
4) Slack channel for that puzzle is updated accordingly.

**Comment by asdfryan** [comment]
Edge cases to consider (perhaps not part of the MVP, but important nonetheless):
1) Duplicate guesses -- I expect this will happen a lot, especially if multiple people are working on the same puzzle. The server should recognize when an answer/puzzle pair has already been added to the queue and not add it.
2) Phone person mistakenly marks a guess as correct/incorrect. 
3) (low priority) Solver has a typo in the guess and would like to remove it from the answer queue.

**Comment by asdfryan** [comment]
I was mistaken, it seems that the answer protocol is submit on website, verify by phone.

In that case, we should have the phone-person be responsible for submitting answers on the website and updating the queue as necessary.
