### ISSUE TITLE
When adding new tag, the color menu should have color

### ISSUE THREAD

**Issue by erwa** [cardinalitypuzzles/smallboard#120]
This is just a polishing, nice-to-have feature. It would be nice if the "blue" and "gray" options below had blue and gray backgrounds.

![color-tags](https://user-images.githubusercontent.com/544734/71588176-8b8bcf00-2aee-11ea-9a1d-c79469316728.png)

**Comment by rgossiaux** [comment]
Going to do this as part of #251 (react rewrite)

**Comment by rgossiaux** [comment]
Ended up not doing this exactly, but the React add tag UI shows a preview of the tag as you're creating it (including the color) which I think solves the problem of wanting to know what the tag is going to look like when you're creating it.
