### ISSUE TITLE
Ability to delete or archive puzzle

### ISSUE THREAD

**Issue by erwa** [cardinalitypuzzles/smallboard#14]
In case a puzzle is created multiple times, it would be useful to be able to delete or archive a puzzle. Deleting is currently possible from the /admin view but not from a normal user's view.

This feature is related to #30.

**Comment by asdfryan** [comment]
Deletion support has been added. Not sure archiving functionality is necessary -- the puzzles page presorting should be intelligent enough to determine puzzles that don't need to be shown (e.g. puzzles whose metas have already been solved?)

**Comment by erwa** [comment]
Yeah, I think deletion is sufficient. Will close this issue.
