### ISSUE TITLE
collapse meta button is missing on page load

### ISSUE THREAD

**Issue by rawxfish** [cardinalitypuzzles/smallboard#159]
When the page first loads, the collapse button is missing but still clickable. It shows up after you collapse and uncollapse though.
![Screen Shot 2020-01-15 at 10 32 44 PM](https://user-images.githubusercontent.com/1312469/72491206-58805580-37e7-11ea-8fa0-9342b537f796.png)

**Comment by erwa** [comment]
Interesting. Seems related to (but even worse than) #119.
