### ISSUE TITLE
Slack API error when creating a puzzle

### ISSUE THREAD

**Issue by rgossiaux** [cardinalitypuzzles/smallboard#166]
```Encountered error adding new puzzle: SlackApiError at /hunts/1/ The request to the Slack API failed. The server responded with: {'ok': False, 'error': 'not_in_channel'} Request Method: POST Request URL: http://smallboard.herokuapp.com/hunts/1/ Django Version: 2.2.9 Python Executable: /app/.heroku/python/bin/python Python Version: 3.6.4 Python Path: ['/app/.heroku/python/bin', '/app', '/app/.heroku/python/lib/python36.zip', '/app/.heroku/python/lib/python3.6', '/app/.heroku/python/lib/python3.6/lib-dynload', '/app/.heroku/python/lib/python3.6/site-packages'] Server time: Fri, 17 Jan 2020 13:30:50 -0500 Installed Applications: ['django.contrib.admin', 'django.contrib.auth', 'django.contrib.contenttypes', 'django.contrib.sessions', 'django.contrib.messages', 'django.contrib.staticfiles', 'puzzles', 'accounts', 'hunts', 'answers', 'social_django', 'taggit'] Installed Middleware: ('whitenoise.middleware.WhiteNoiseMiddleware', 'django.middleware.security.SecurityMiddleware', 'whitenoise.middleware.WhiteNoiseMiddleware', 'django.contrib.sessions.middleware.SessionMiddleware', 'django.middleware.common.CommonMiddleware', 'django.middleware.csrf.CsrfViewMiddleware', 'django.contrib.auth.middleware.AuthenticationMiddleware', 'django.contrib.messages.middleware.MessageMiddleware', 'django.middleware.clickjacking.XFrameOptionsMiddleware', 'social_django.middleware.SocialAuthExceptionMiddleware') Traceback: File "/app/.heroku/python/lib/python3.6/site-packages/django/core/handlers/exception.py" in inner 34. response = get_response(request) File "/app/.heroku/python/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response 115. response = self.process_exception_by_middleware(e, request) File "/app/.heroku/python/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response 113. response = wrapped_callback(request, *callback_args, **callback_kwargs) File "/app/.heroku/python/lib/python3.6/site-packages/django/views/generic/base.py" in view 71. return self.dispatch(request, *args, **kwargs) File "/app/.heroku/python/lib/python3.6/site-packages/django/utils/decorators.py" in _wrapper 45. return bound_method(*args, **kwargs) File "/app/.heroku/python/lib/python3.6/site-packages/django/views/decorators/csrf.py" in wrapped_view 54. return view_func(*args, **kwargs) File "/app/.heroku/python/lib/python3.6/site-packages/django/contrib/auth/mixins.py" in dispatch 52. return super().dispatch(request, *args, **kwargs) File "/app/.heroku/python/lib/python3.6/site-packages/django/views/generic/base.py" in dispatch 97. return handler(request, *args, **kwargs) File "/app/hunts/views.py" in post 190. is_meta) File "/app/slack_lib/slack_client.py" in announce_puzzle_creation 87. sheet_url)) File "/app/slack_lib/slack_client.py" in announce 58. self.send_message(self.announcement_channel_name, message) File "/app/slack_lib/slack_client.py" in send_message 69. self._web_client.chat_postMessage(channel=channel, text=message) File "/app/.heroku/python/lib/python3.6/site-packages/slack/web/client.py" in chat_postMessage 382. return self.api_call("chat.postMessage", json=kwargs) File "/app/.heroku/python/lib/python3.6/site-packages/slack/web/base_client.py" in api_call 172. return self._event_loop.run_until_complete(future) File "/app/.heroku/python/lib/python3.6/asyncio/base_events.py" in run_until_complete 467. return future.result() File "/app/.heroku/python/lib/python3.6/site-packages/slack/web/base_client.py" in _send 241. return SlackResponse(**{**data, **res}).validate() File "/app/.heroku/python/lib/python3.6/site-packages/slack/web/slack_response.py" in validate 176. raise e.SlackApiError(message=msg, response=self) Exception Type: SlackApiError at /hunts/1/ Exception Value: The request to the Slack API failed. The server responded with: {'ok': False, 'error': 'not_in_channel'} Request information: USER: Ryan Gossiaux GET: No GET data POST: csrfmiddlewaretoken = '9N0d2ygm5ytvyUBLZAsDFlwiVx7Ip65gsCyjMucGZ80JtJ66RgL0f2p4Pc7a5Czo' name = 'Goldilocks' url = 'https://pennypark.fun/puzzle/goldilocks' FILES: No FILES data COOKIES: csrftoken = '05EBwbQUSLJBLIHuV7uMms1g8W3w5c4BjUcHg7MeMlgPGxcPNNN9W9U22B3YLIyJ' sessionid = 'jzncz3ieb6ifwhppi2d9eliswhhwkbmw' META: CONTENT_LENGTH = '154' CONTENT_TYPE = 'application/x-www-form-urlencoded; charset=UTF-8' CSRF_COOKIE = '05EBwbQUSLJBLIHuV7uMms1g8W3w5c4BjUcHg7MeMlgPGxcPNNN9W9U22B3YLIyJ' HTTP_ACCEPT = '*/*' HTTP_ACCEPT_ENCODING = 'gzip, deflate' HTTP_ACCEPT_LANGUAGE = 'en-US,en;q=0.9,es;q=0.8' HTTP_CONNECTION = 'close' HTTP_CONNECT_TIME = '0' HTTP_COOKIE = 'csrftoken=05EBwbQUSLJBLIHuV7uMms1g8W3w5c4BjUcHg7MeMlgPGxcPNNN9W9U22B3YLIyJ; sessionid=jzncz3ieb6ifwhppi2d9eliswhhwkbmw' HTTP_HOST = 'smallboard.herokuapp.com' HTTP_ORIGIN = 'http://smallboard.herokuapp.com' HTTP_REFERER = 'http://smallboard.herokuapp.com/hunts/1/' HTTP_TOTAL_ROUTE_TIME = '0' HTTP_USER_AGENT = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36' HTTP_VIA = '1.1 vegur' HTTP_X_FORWARDED_FOR = '18.21.179.51' HTTP_X_FORWARDED_PORT = '80' HTTP_X_FORWARDED_PROTO = 'http' HTTP_X_REQUESTED_WITH = 'XMLHttpRequest' HTTP_X_REQUEST_ID = '55a6269b-6c3d-499a-8ab5-a948688bdeec' HTTP_X_REQUEST_START = '1579285840713' PATH_INFO = '/hunts/1/' QUERY_STRING = '' RAW_URI = '/hunts/1/' REMOTE_ADDR = '10.45.182.145' REMOTE_PORT = '17686' REQUEST_METHOD = 'POST' SCRIPT_NAME = '' SERVER_NAME = '0.0.0.0' SERVER_PORT = '58364' SERVER_PROTOCOL = 'HTTP/1.1' SERVER_SOFTWARE = 'gunicorn/20.0.0' gunicorn.socket = wsgi.errors = wsgi.file_wrapper = '' wsgi.input = wsgi.input_terminated = False wsgi.multiprocess = True wsgi.multithread = False wsgi.run_once = False wsgi.url_scheme = 'http' wsgi.version = '(1, 0)' Settings: Using settings module smallboard.settings ABSOLUTE_URL_OVERRIDES = {} ACTIVE_HUNT_ID = '1' ADMINS = [] ALLOWED_HOSTS = ['*'] APPEND_SLASH = True AUTHENTICATION_BACKENDS = ['social_core.backends.google.GoogleOAuth2', 'django.contrib.auth.backends.ModelBackend'] AUTH_PASSWORD_VALIDATORS = '********************' AUTH_USER_MODEL = 'accounts.Puzzler' BASE_DIR = '/app' CACHES = {'default': {'BACKEND': 'django.core.cache.backends.locmem.LocMemCache'}} CACHE_MIDDLEWARE_ALIAS = 'default' CACHE_MIDDLEWARE_KEY_PREFIX = '********************' CACHE_MIDDLEWARE_SECONDS = 600 CSRF_COOKIE_AGE = 31449600 CSRF_COOKIE_DOMAIN = None CSRF_COOKIE_HTTPONLY = False CSRF_COOKIE_NAME = 'csrftoken' CSRF_COOKIE_PATH = '/' CSRF_COOKIE_SAMESITE = 'Lax' CSRF_COOKIE_SECURE = False CSRF_FAILURE_VIEW = 'django.views.csrf.csrf_failure' CSRF_HEADER_NAME = 'HTTP_X_CSRFTOKEN' CSRF_TRUSTED_ORIGINS = [] CSRF_USE_SESSIONS = False DATABASES = {'default': {'NAME': 'd68a0gedg6rhqr', 'USER': 'hshsvdetiyxvyv', 'PASSWORD': '********************', 'HOST': 'ec2-174-129-253-146.compute-1.amazonaws.com', 'PORT': 5432, 'CONN_MAX_AGE': 600, 'ENGINE': 'django.db.backends.postgresql_psycopg2', 'TEST': {'NAME': 'test_smallboard', 'CHARSET': None, 'COLLATION': None, 'MIRROR': None}, 'ATOMIC_REQUESTS': False, 'AUTOCOMMIT': True, 'OPTIONS': {}, 'TIME_ZONE': None}} DATABASE_ROUTERS = [] DATA_UPLOAD_MAX_MEMORY_SIZE = 2621440 DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000 DATETIME_FORMAT = 'N j, Y, P' DATETIME_INPUT_FORMATS = ['%Y-%m-%d %H:%M:%S', '%Y-%m-%d %H:%M:%S.%f', '%Y-%m-%d %H:%M', '%Y-%m-%d', '%m/%d/%Y %H:%M:%S', '%m/%d/%Y %H:%M:%S.%f', '%m/%d/%Y %H:%M', '%m/%d/%Y', '%m/%d/%y %H:%M:%S', '%m/%d/%y %H:%M:%S.%f', '%m/%d/%y %H:%M', '%m/%d/%y'] DATE_FORMAT = 'N j, Y' DATE_INPUT_FORMATS = ['%Y-%m-%d', '%m/%d/%Y', '%m/%d/%y', '%b %d %Y', '%b %d, %Y', '%d %b %Y', '%d %b, %Y', '%B %d %Y', '%B %d, %Y', '%d %B %Y', '%d %B, %Y'] DEBUG = True DEBUG_PROPAGATE_EXCEPTIONS = False DECIMAL_SEPARATOR = '.' DEFAULT_CHARSET = 'utf-8' DEFAULT_CONTENT_TYPE = 'text/html' DEFAULT_EXCEPTION_REPORTER_FILTER = 'django.views.debug.SafeExceptionReporterFilter' DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage' DEFAULT_FROM_EMAIL = 'webmaster@localhost' DEFAULT_INDEX_TABLESPACE = '' DEFAULT_TABLESPACE = '' DISALLOWED_USER_AGENTS = [] EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend' EMAIL_HOST = 'localhost' EMAIL_HOST_PASSWORD = '********************' EMAIL_HOST_USER = '' EMAIL_PORT = 25 EMAIL_SSL_CERTFILE = None EMAIL_SSL_KEYFILE = '********************' EMAIL_SUBJECT_PREFIX = '[Django] ' EMAIL_TIMEOUT = None EMAIL_USE_LOCALTIME = False EMAIL_USE_SSL = False EMAIL_USE_TLS = False FILE_CHARSET = 'utf-8' FILE_UPLOAD_DIRECTORY_PERMISSIONS = None FILE_UPLOAD_HANDLERS = ['django.core.files.uploadhandler.MemoryFileUploadHandler', 'django.core.files.uploadhandler.TemporaryFileUploadHandler'] FILE_UPLOAD_MAX_MEMORY_SIZE = 2621440 FILE_UPLOAD_PERMISSIONS = None FILE_UPLOAD_TEMP_DIR = None FIRST_DAY_OF_WEEK = 0 FIXTURE_DIRS = [] FORCE_SCRIPT_NAME = None FORMAT_MODULE_PATH = None FORM_RENDERER = 'django.forms.renderers.DjangoTemplates' GOOGLE_API_AUTHN_INFO = '********************' GOOGLE_DRIVE_HUNT_FOLDER_ID = '127neQGZIdJfh0CtbkAWZOK1KoD8i-ZNu' GOOGLE_DRIVE_PERMISSIONS_SCOPES = ['https://www.googleapis.com/auth/drive'] GOOGLE_SHEETS_TEMPLATE_FILE_ID = '1EI9M5l0qiQ7BDQoDuGpVsiL52JxiMBVHD5qKEOq7M4A' IGNORABLE_404_URLS = [] INSTALLED_APPS = ['django.contrib.admin', 'django.contrib.auth', 'django.contrib.contenttypes', 'django.contrib.sessions', 'django.contrib.messages', 'django.contrib.staticfiles', 'puzzles', 'accounts', 'hunts', 'answers', 'social_django', 'taggit'] INTERNAL_IPS = [] LANGUAGES = [('af', 'Afrikaans'), ('ar', 'Arabic'), ('ast', 'Asturian'), ('az', 'Azerbaijani'), ('bg', 'Bulgarian'), ('be', 'Belarusian'), ('bn', 'Bengali'), ('br', 'Breton'), ('bs', 'Bosnian'), ('ca', 'Catalan'), ('cs', 'Czech'), ('cy', 'Welsh'), ('da', 'Danish'), ('de', 'German'), ('dsb', 'Lower Sorbian'), ('el', 'Greek'), ('en', 'English'), ('en-au', 'Australian English'), ('en-gb', 'British English'), ('eo', 'Esperanto'), ('es', 'Spanish'), ('es-ar', 'Argentinian Spanish'), ('es-co', 'Colombian Spanish'), ('es-mx', 'Mexican Spanish'), ('es-ni', 'Nicaraguan Spanish'), ('es-ve', 'Venezuelan Spanish'), ('et', 'Estonian'), ('eu', 'Basque'), ('fa', 'Persian'), ('fi', 'Finnish'), ('fr', 'French'), ('fy', 'Frisian'), ('ga', 'Irish'), ('gd', 'Scottish Gaelic'), ('gl', 'Galician'), ('he', 'Hebrew'), ('hi', 'Hindi'), ('hr', 'Croatian'), ('hsb', 'Upper Sorbian'), ('hu', 'Hungarian'), ('hy', 'Armenian'), ('ia', 'Interlingua'), ('id', 'Indonesian'), ('io', 'Ido'), ('is', 'Icelandic'), ('it', 'Italian'), ('ja', 'Japanese'), ('ka', 'Georgian'), ('kab', 'Kabyle'), ('kk', 'Kazakh'), ('km', 'Khmer'), ('kn', 'Kannada'), ('ko', 'Korean'), ('lb', 'Luxembourgish'), ('lt', 'Lithuanian'), ('lv', 'Latvian'), ('mk', 'Macedonian'), ('ml', 'Malayalam'), ('mn', 'Mongolian'), ('mr', 'Marathi'), ('my', 'Burmese'), ('nb', 'Norwegian Bokmål'), ('ne', 'Nepali'), ('nl', 'Dutch'), ('nn', 'Norwegian Nynorsk'), ('os', 'Ossetic'), ('pa', 'Punjabi'), ('pl', 'Polish'), ('pt', 'Portuguese'), ('pt-br', 'Brazilian Portuguese'), ('ro', 'Romanian'), ('ru', 'Russian'), ('sk', 'Slovak'), ('sl', 'Slovenian'), ('sq', 'Albanian'), ('sr', 'Serbian'), ('sr-latn', 'Serbian Latin'), ('sv', 'Swedish'), ('sw', 'Swahili'), ('ta', 'Tamil'), ('te', 'Telugu'), ('th', 'Thai'), ('tr', 'Turkish'), ('tt', 'Tatar'), ('udm', 'Udmurt'), ('uk', 'Ukrainian'), ('ur', 'Urdu'), ('vi', 'Vietnamese'), ('zh-hans', 'Simplified Chinese'), ('zh-hant', 'Traditional Chinese')] LANGUAGES_BIDI = ['he', 'ar', 'fa', 'ur'] LANGUAGE_CODE = 'en-us' LANGUAGE_COOKIE_AGE = None LANGUAGE_COOKIE_DOMAIN = None LANGUAGE_COOKIE_NAME = 'django_language' LANGUAGE_COOKIE_PATH = '/' LOCALE_PATHS = [] LOGGING = {'version': 1, 'disable_existing_loggers': False, 'formatters': {'verbose': {'format': '%(asctime)s [%(process)d] [%(levelname)s] pathname=%(pathname)s lineno=%(lineno)s funcname=%(funcName)s %(message)s', 'datefmt': '%Y-%m-%d %H:%M:%S'}, 'simple': {'format': '%(levelname)s %(message)s'}}, 'handlers': {'null': {'level': 'DEBUG', 'class': 'logging.NullHandler'}, 'console': {'level': 'DEBUG', 'class': 'logging.StreamHandler', 'formatter': 'verbose'}}, 'loggers': {'testlogger': {'handlers': ['console'], 'level': 'INFO'}}} LOGGING_CONFIG = 'logging.config.dictConfig' LOGIN_ERROR_URL = '/' LOGIN_REDIRECT_URL = '/' LOGIN_URL = '/accounts/login/' LOGOUT_REDIRECT_URL = '/' MANAGERS = [] MEDIA_ROOT = '' MEDIA_URL = '' MESSAGE_STORAGE = 'django.contrib.messages.storage.fallback.FallbackStorage' MIDDLEWARE = "('whitenoise.middleware.WhiteNoiseMiddleware', 'django.middleware.security.SecurityMiddleware', 'whitenoise.middleware.WhiteNoiseMiddleware', 'django.contrib.sessions.middleware.SessionMiddleware', 'django.middleware.common.CommonMiddleware', 'django.middleware.csrf.CsrfViewMiddleware', 'django.contrib.auth.middleware.AuthenticationMiddleware', 'django.contrib.messages.middleware.MessageMiddleware', 'django.middleware.clickjacking.XFrameOptionsMiddleware', 'social_django.middleware.SocialAuthExceptionMiddleware')" MIGRATION_MODULES = {} MONTH_DAY_FORMAT = 'F j' NUMBER_GROUPING = 0 PASSWORD_HASHERS = '********************' PASSWORD_RESET_TIMEOUT_DAYS = '********************' PREPEND_WWW = False ROOT_URLCONF = 'smallboard.urls' SECRET_KEY = '********************' SECURE_BROWSER_XSS_FILTER = False SECURE_CONTENT_TYPE_NOSNIFF = False SECURE_HSTS_INCLUDE_SUBDOMAINS = False SECURE_HSTS_PRELOAD = False SECURE_HSTS_SECONDS = 0 SECURE_PROXY_SSL_HEADER = None SECURE_REDIRECT_EXEMPT = [] SECURE_SSL_HOST = None SECURE_SSL_REDIRECT = False SERVER_EMAIL = 'root@localhost' SESSION_CACHE_ALIAS = 'default' SESSION_COOKIE_AGE = 1209600 SESSION_COOKIE_DOMAIN = None SESSION_COOKIE_HTTPONLY = True SESSION_COOKIE_NAME = 'sessionid' SESSION_COOKIE_PATH = '/' SESSION_COOKIE_SAMESITE = 'Lax' SESSION_COOKIE_SECURE = False SESSION_ENGINE = 'django.contrib.sessions.backends.db' SESSION_EXPIRE_AT_BROWSER_CLOSE = False SESSION_FILE_PATH = None SESSION_SAVE_EVERY_REQUEST = False SESSION_SERIALIZER = 'django.contrib.sessions.serializers.JSONSerializer' SETTINGS_MODULE = 'smallboard.settings' SHORT_DATETIME_FORMAT = 'm/d/Y P' SHORT_DATE_FORMAT = 'm/d/Y' SIGNING_BACKEND = 'django.core.signing.TimestampSigner' SILENCED_SYSTEM_CHECKS = [] SLACK_API_TOKEN = '********************' SLACK_BASE_URL = 'https://cardinality-puzzles.slack.com' SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '********************' SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = '********************' SOCIAL_AUTH_GOOGLE_OAUTH2_WHITELISTED_EMAILS = ['Axxonnfire@gmail.com', 'Dennis.Z.Mou@gmail.com', 'JamesDHitchcock@gmail.com', 'PeterCVera@gmail.com', 'Sekishi.Kei.Ou@gmail.com', 'Sutherlin.K@gmail.com', 'abejnood@gmail.com', 'akira.baruah@gmail.com', 'alisonychang6@gmail.com', 'amruthv@gmail.com', 'asdfryan123@gmail.com', 'axxonnfire@gmail.com', 'bhhnguyen@gmail.com', 'bridget.fidgets@gmail.com', 'caesural@gmail.com', 'cardinality-mitmh2020@googlegroups.com', 'cardinalitypuzzles@gmail.com', 'carissa555@gmail.com', 'daiweili@gmail.com', 'dennis.z.mou@gmail.com', 'edv.emails@gmail.com', 'erwaman@gmail.com', 'james.adam.buckland@gmail.com', 'jamesdhitchcock@gmail.com', 'jchan3580@gmail.com', 'jekbradbury@gmail.com', 'josh.w0@gmail.com', 'joysun.sb@gmail.com', 'jthurst3@u.rochester.edu', 'kevin.c.lin@gmail.com', 'kuobenj@gmail.com', 'li.janet.2001@gmail.com', 'maxwimberley@gmail.com', 'millercs624@gmail.com', 'minhtue90@gmail.com', 'moo.bamboo@gmail.com', 'neutral13@gmail.com', 'oanamursu@gmail.com', 'petercvera@gmail.com', 'phantomofthepiano@gmail.com', 'rasinghsidhu@gmail.com', 'rose.yin@gmail.com', 'ryan.gossiaux@gmail.com', 'sekishi.kei.ou@gmail.com', 'shreyes19@gmail.com', 'shubo.yin@aya.yale.edu', 'shuxinzhan@gmail.com', 'smallboard-test@smallboard-test-260001.iam.gserviceaccount.com', 'sutherlin.k@gmail.com', 'watermaximillion@gmail.com', 'yoojinpia@gmail.com'] SOCIAL_AUTH_URL_NAMESPACE = 'social' STATICFILES_DIRS = ['/app/smallboard/static'] STATICFILES_FINDERS = ['django.contrib.staticfiles.finders.FileSystemFinder', 'django.contrib.staticfiles.finders.AppDirectoriesFinder'] STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage' STATIC_ROOT = '/app/staticfiles' STATIC_URL = '/static/' TAGGIT_TAGS_FROM_STRING = 'puzzles.tag_utils.to_tag' TEMPLATES = [{'BACKEND': 'django.template.backends.django.DjangoTemplates', 'DIRS': ['smallboard/templates/'], 'APP_DIRS': True, 'OPTIONS': {'context_processors': ['django.template.context_processors.debug', 'django.template.context_processors.request', 'django.contrib.auth.context_processors.auth', 'django.contrib.messages.context_processors.messages', 'social_django.context_processors.backends', 'social_django.context_processors.login_redirect', 'smallboard.context_processors.google_auth']}}] TEST_NON_SERIALIZED_APPS = [] TEST_RUNNER = 'django.test.runner.DiscoverRunner' THOUSAND_SEPARATOR = ',' TIME_FORMAT = 'P' TIME_INPUT_FORMATS = ['%H:%M:%S', '%H:%M:%S.%f', '%H:%M'] TIME_ZONE = 'America/New_York' USE_I18N = True USE_L10N = True USE_THOUSAND_SEPARATOR = False USE_TZ = True USE_X_FORWARDED_HOST = False USE_X_FORWARDED_PORT = False WSGI_APPLICATION = 'smallboard.wsgi.application' X_FRAME_OPTIONS = 'SAMEORIGIN' YEAR_MONTH_FORMAT = 'F Y' You're seeing this error because you have DEBUG = True in your Django settings file. Change that to False, and Django will display a standard page generated by the handler for this status code.```

**Comment by rgossiaux** [comment]
Looks like this led to us not being able to mark Goldilocks correct @erwa

**Comment by erwa** [comment]
I believe this was due to the cardinalitypuzzles@gmail.com user not being part of the #puzzle-announcements page (configured in https://github.com/cardinalitypuzzles/smallboard/blob/master/slack_lib/slack_client.py#L31). We should add some code to join the channel first on start-up in case we are not already part of it.
