### ISSUE TITLE
Remove Answer Queue page

### ISSUE THREAD

**Issue by erwa** [cardinalitypuzzles/smallboard#167]
At the 2020 MITMH, answers were automatically verified. There were no phone calls for confirming answers. It seems likely that going forward, answers will be auto-confirmed. Thus, we can remove the Answer Queue page and merge its functionality with the main puzzle page.

**Comment by rawxfish** [comment]
Should we assume all answers entered into the smallboard are correct and just have option to add or remove answers?

**Comment by akirabaruah** [comment]
Maybe we can still add answers (not remove) and leave the option of updating their "statuses"? I think that's essentially how the answer queue works now, but we can probably consolidate the functionality into the puzzle pages themselves.

I think it'd still be helpful to log previous (incorrect/partial) answers for each puzzle to provide context for folks jumping in to solve. If we intend to rely on the puzzle hunt's site to track previous answers, then keeping only one Answer per Puzzle should work.

**Comment by rawxfish** [comment]
I assume when we are aggressively backsolving or making educated guesses, we will just use the puzzle hunt's site to track previous answers. However, last year's hunt had multiple answers per puzzle, so I like the idea of having the option to log previous partial/incorrect answers since it can also be used to track multiple correct answers.

**Comment by akirabaruah** [comment]
Makes sense 👍  yeah in that case, if we're going to support multiple answers, we should definitely continue to support editing the different statuses.

> Should we assume all answers entered into the smallboard are correct and just have option to add or remove answers?
Adding answers seems straightforward. Why would we want to remove answers? (I'm struggling to think of an example scenario that would require it)

**Comment by erwa** [comment]
Oh right, I forgot there were puzzles with multiple correct answers in MITMH 2020. That's something we might want to support in the future. I created https://github.com/cardinalitypuzzles/smallboard/issues/196 for this.

**Comment by akirabaruah** [comment]
So for the purposes of removing the Answer queue page, what do y'all think of replacing the queue with per-Puzzle status pages that include simple lists of all Answers for each individual puzzle? That should be relatively simple to add and would support multiple "correct" answers out of the box.

Or maybe even simpler: support multiple "correct" answers on the main puzzles list page?

**Comment by erwa** [comment]
I think the main puzzles list page should show all "correct" answers.

For a list of all submitted answers (some of which might be partial answers), I think it'd be nice if that could be a hover-over or on-click pop-up on the puzzles list page, but I think having a separate page per puzzle is fine, too.

We still need some way of marking an answer as PENDING/PARTIAL/CORRECT/INCORRECT -- it'd be nice if you could change that status from the main puzzles page.

**Comment by rgossiaux** [comment]
IMO we should put the existing answer queue functionality behind a flag for future mystery hunts, there's no guarantee that the next writing team won't bring back phoning in answers given its long history at mystery hunt

**Comment by akirabaruah** [comment]
> For a list of all submitted answers (some of which might be partial answers), I think it'd be nice if that could be a hover-over or on-click pop-up on the puzzles list page, but I think having a separate page per puzzle is fine, too.

Yeah, maybe a simple drop-down toggle for incorrect/partial answers should suffice?

> We still need some way of marking an answer as PENDING/PARTIAL/CORRECT/INCORRECT -- it'd be nice if you could change that status from the main puzzles page.

Agreed :+1: I'm envisioning an "edit" icon similar to the one next to the `Name` field to let folks modify the ANSWER text and status.
