### ISSUE TITLE
Small Board should support emojis

### ISSUE THREAD

**Issue by erwa** [cardinalitypuzzles/smallboard#168]
At the MITMH 2020, there were some answers that were emojis. Small Board currently strips all non A-Z or 0-9 characters:
* https://github.com/cardinalitypuzzles/smallboard/blob/master/puzzles/templates/modals/submit_answer.html#L42-L44
* https://github.com/cardinalitypuzzles/smallboard/blob/master/puzzles/views.py#L49-L50

We may want to allow emojis for future hunts.

**Comment by asdfryan** [comment]
We should potentially allow any sort of arbitrary characters (foreign languages, special chars, etc.).
