### ISSUE TITLE
Scripts broken in cloned template spreadsheet

### ISSUE THREAD

**Issue by erwa** [cardinalitypuzzles/smallboard#169]
When the template Google spreadsheet was cloned for each puzzle, the JavaScript functions (as illustrated in the "Examples" tab) did not work for some reason. If you manually copy the spreadsheet, the JavaScript does work.

**Comment by rgossiaux** [comment]
I feel like someone fixed this already a long while ago but if not we should definitely address this before hunt this year.

**Comment by rawxfish** [comment]
sooooooooooo this is actually broken. 

![image](https://user-images.githubusercontent.com/1312469/104084828-c4d63f00-5218-11eb-96f3-e3494a84c0cb.png)
