### ISSUE TITLE
CSRF verification failure happens intermittently when users create puzzles concurrently

### ISSUE THREAD

**Issue by erwa** [cardinalitypuzzles/smallboard#172]
During the MITMH 2020, we saw this error intermittently:

![csrf-verification](https://user-images.githubusercontent.com/544734/72849528-e25f7100-3c74-11ea-8a34-7978b1fdc393.png)

It seems to happen when several users are creating puzzles simultaneously.

**Comment by asdfryan** [comment]
This happened to me when I tried to make multiple puzzles without refreshing the page. AFAIK I was the only one creating puzzles, so it might not have to do with multiple users trying to create puzzles simultaneously.

**Comment by rgossiaux** [comment]
Going to just close this; we can't repro and I think the most likely thing is that you got logged out
