### ISSUE TITLE
Automatic Discord channel creation (text + voice)

### ISSUE THREAD

**Issue by akirabaruah** [cardinalitypuzzles/smallboard#186]
Features:
- voice chat
- text chat (similar to existing Slack integration)

**Comment by rawxfish** [comment]
Current plan:

- Ask everyone to switch notifications for the server to "Only @mentions" 
- New puzzle should create text channel under "puzzle" category. The new channel will be announced in an announcements, maybe with @everyone (or we can make this opt-in with a role or sth) 
- Solving puzzle should move text channel from "puzzle" category to "archive" category
- Voice channels can be flexibly created or renamed, and not linked with smallboard. The best practice should be for people to rename VCs to name of puzzles worked on

It might also be nice for smallboard to name text channels with emojis to indicate whether they're meta / high priority / low priority.

**Comment by rgossiaux** [comment]
Just curious, why can't smallboard create audio channels as well?

**Comment by rawxfish** [comment]
We could do that. I was worried it'd be cluttered if we accumulate a lot of open puzzles?

**Comment by rawxfish** [comment]
As a side note, can we name our discord bot Cardi T

**Comment by akirabaruah** [comment]
> We could do that. I was worried it'd be cluttered if we accumulate a lot of open puzzles?

I guess we can collapse the "Voice Channels" tab if needed? Seems like it's the same situation as with text channels? (maybe this was discussed in the last face-to-face sync) Ideally, we'd have some way to group the text and voice channels for a particular puzzle together, but right now, it seems like Discord keeps text and voice separate.

**Comment by rgossiaux** [comment]
Yeah it might be nice for people to not have to worry about creating them, I guess it's going to be more technically complex though. We'd need to delete them after the puzzles got solved, but maybe only when they're empty (it'd be super rude if you just finished a puzzle and got booted out of the voice channel before you could celebrate/discuss with the other solvers), so maybe a cron job (or similar, I think Heroku has a scheduler product) would clean them up periodically, or if that's too much work someone running a script every once in a while

**Comment by rawxfish** [comment]
Is it thaaaaat rude? We could move them to a general "water cooler" voice channel. Might be sorta hype for the people in water cooler since they'd know a puzzle just got solved.

**Comment by asdfryan** [comment]
+1 to also opening a voice channel and periodic clean-up cron (1x an hour should be sufficient IMO). The cron job can take care of both voice + text channels IMO

In the interest of getting this done, can we split up this issue into a couple smaller ones? 
- Auto-creation of text + voice channels upon puzzle creation (MVP)
- Aforementioned cron job for GCing channels when puzzles have been solved and voice channels are empty
- Auto-messaging upon puzzle creation + solves

**Comment by akirabaruah** [comment]
> Is it thaaaaat rude? We could move them to a general "water cooler" voice channel. Might be sorta hype for the people in water cooler since they'd know a puzzle just got solved. 

Interesting - kinda like that feeling you get when you finish an escape room?

**Comment by akirabaruah** [comment]
Copying @asdfryan's research from our chat:

> there are 2 main issues:
> 1) discord.py is an asyncio-based API -- all of our discord features (channel creation, channel deletion, publish messages) are synchronous, so it makes for awkward code construction
> 2) the discord client run() function brings up a listener, and is a blocking function and does not play well with Django. We'd have to bring up a daemon thread just for the discord client, and have the discord client listen to events spawned from the main thread

**Comment by akirabaruah** [comment]
Now that we've merged the core functionality for creating channels, we should integrate it into the React API and UI as part of #251

**Comment by rgossiaux** [comment]
What's the remaining work for this?

**Comment by asdfryan** [comment]
This is done. The remaining discord items are tracked in other issues.

**Comment by akirabaruah** [comment]
I think we might be done here :+1:

**Comment by akirabaruah** [comment]
Ah @asdfryan beat me to it :smile:
