### ISSUE TITLE
Add LICENSE file to repo

### ISSUE THREAD

**Issue by erwa** [cardinalitypuzzles/smallboard#19]
I suggest Apache or MIT License, which are both fairly unrestrictive.

**Comment by akirabaruah** [comment]
I agree. Maybe we should just go with MIT since there probably won't be any patents involved with this project.

Also, the hunt is at MIT, so it seems pretty fitting ;)

**Comment by erwa** [comment]
Haha, MIT License is pretty fitting for this repo.
