### ISSUE TITLE
Support multiple answers per puzzle

### ISSUE THREAD

**Issue by erwa** [cardinalitypuzzles/smallboard#196]
For MITMH 2020, there were some puzzles that had multiple answers (e.g.: the [Safari Adventure puzzles](https://www.mit.edu/~puzzle/2020/land/safari/)). It would be nice to support this on Smallboard. That said, multiple answers per puzzle probably won't come up in many hunts, so this is not that high priority, I'd say.

**Comment by asdfryan** [comment]
Totally forgot about this -- how'd we deal with this last year?

**Comment by rawxfish** [comment]
We just concatenated all of the answers and manually separated them later

**Comment by rgossiaux** [comment]
We have support for this now as of #275 although I think we still need to iterate on the UI (tracked in #280)
