### ISSUE TITLE
Complete Google OAuth verification

### ISSUE THREAD

**Issue by rawxfish** [cardinalitypuzzles/smallboard#197]
We use google oauth to make sure only people with access to the drive can access smallboard.

https://support.google.com/cloud/answer/9110914?hl=en

I added a privacy page but apparently our home page also needs work:

![image](https://user-images.githubusercontent.com/1312469/100050302-1fd9e100-2de7-11eb-8118-6990e8bb798e.png)

**Comment by akirabaruah** [comment]
Sounds like we might want to add a generic home page that explains what smallboard is and link to the privacy policy?

**Comment by rawxfish** [comment]
We got a followup email today:

![image](https://user-images.githubusercontent.com/1312469/100827253-51c3f680-342a-11eb-97ee-d7cada8c16f0.png)

Do you guys think this is sufficient for the home page:

![Screen Shot 2020-12-01 at 11 11 48 PM](https://user-images.githubusercontent.com/1312469/100827399-9bacdc80-342a-11eb-803c-a88ec343ff6e.png)

**Comment by akirabaruah** [comment]
LGTM overall - thanks for keeping tabs on this - a couple things we might want to clarify:

- the whitelist of emails ensures that only authorized users access the site (as an aside, do we want to eventually open it up to the public?)
- under "How do I join a hunt?" - emailing us will only let you access this app, not actually add you to <insert puzzle hunt name here>

**Comment by rgossiaux** [comment]
Maybe we could mark it internal-only for now? Do we qualify for that? Might be easier than wrangling with them.

**Comment by rawxfish** [comment]
I think internal-only means setting up an organization and giving everyone an org email: https://support.google.com/cloud/answer/6158849#public-and-internal

**Comment by rawxfish** [comment]
> the whitelist of emails ensures that only authorized users access the site (as an aside, do we want to eventually open it up to the public?)

I'm worried that if the language isn't public facing, they'd make us be an internal app and pay money to be an org...

> under "How do I join a hunt?" - emailing us will only let you access this app, not actually add you to

How about "How do I get whitelisted?"

**Comment by akirabaruah** [comment]
Yeah, at this point, do you think it's easier to put up this new homepage vs. set up individual user emails under a private org?

Depending on how much/little Google nit-picks your proposed homepage, it seems like we're almost there in terms of being a public Google-approved app?

**Comment by akirabaruah** [comment]
> I'm worried that if the language isn't public facing, they'd make us be an internal app and pay money to be an org...

Oh yeah good point about the wording. Also, in the long run, it'd be great to be able to support anyone who wants to use this app 😄 (not sure how to finance scaling to an arbitrary numbers of users, but it seems like a nice goal)

**Comment by rgossiaux** [comment]
Lol kind of ridiculous. I say do whatever you think will make them approve us for now (your screenshot lgtm).

**Comment by rawxfish** [comment]
Gonna make a separate comment for each of the next steps.

Not sure what we have to do for this one, apart from verified domain. I'll re-read the privacy policy that I autogenerated and see if it's missing any of those things and maybe add a footer with the privacy policy link so it's always accessible. 

![image](https://user-images.githubusercontent.com/1312469/101065336-08c38d80-3563-11eb-9c5a-3df5c20e3373.png)

**Comment by rawxfish** [comment]
@rgossiaux I think I need your help with verifying https://smallboard.app/. I'll remove the Heroku link.

![image](https://user-images.githubusercontent.com/1312469/101065527-42949400-3563-11eb-931e-6987886cc9de.png)

**Comment by rawxfish** [comment]
Turns out using the Google sign in asset is not just for kissing up purposes but also a requirement. Just gonna remove the "Login" in the top bar. 

![image](https://user-images.githubusercontent.com/1312469/101065660-6952ca80-3563-11eb-8626-e7b3a3b27a81.png)

![image](https://user-images.githubusercontent.com/1312469/101065844-a5862b00-3563-11eb-8806-51e4badedec7.png)

**Comment by rawxfish** [comment]
Our current consent screen icon URL is the red Twitter bird emoji. Our favicon is big chungus and I don't think we have any icon on the home page (unless they mean the "Cardinality" text). Anyone with thoughts about which icon we should unify under?

![image](https://user-images.githubusercontent.com/1312469/101066007-dd8d6e00-3563-11eb-9b8c-a2d20bc1fa2f.png)

**Comment by rgossiaux** [comment]
smh. Big chungus sounds good to me lol. I just verified smallboard.app.

**Comment by akirabaruah** [comment]
Big chungus sgtm too, although it does seem to be more of inside joke whereas the red bird might make more sense as a Cardinality brand? Can we float this decision by the rest of the dev group?

(wow they really nitpick everything - I guess it's good for consistency/safety)

**Comment by rawxfish** [comment]
We did it.

![image](https://user-images.githubusercontent.com/1312469/102738490-49b7f200-4318-11eb-815a-aeb158360486.png)
