### ISSUE TITLE
Monitoring

### ISSUE THREAD

**Issue by rgossiaux** [cardinalitypuzzles/smallboard#207]
Might be nice to have some automatic monitoring in place and a PagerDuty loop during mystery hunt (looks like we can have up to 5 people on a rotation for free). That way if something horrible happens to smallboard during the hunt, someone will always be on call to handle it.

**Comment by asdfryan** [comment]
Just setting up a PagerDuty rotation to cover 24-7 is sufficient here.

**Comment by asdfryan** [comment]
Spreadsheet + people's phone numbers could be sufficient.

**Comment by rgossiaux** [comment]
Related to this I set up a Coralogix integration today for ingesting our heroku logs, and I hooked it up to the smallboard dev Discord channel with a few basic alerts in the channel if our dyno crashes or we exceed the free tier or anything like that.

**Comment by asdfryan** [comment]
Published oncall rotation sheet on discord.
