### ISSUE TITLE
Discord bot

### ISSUE THREAD

**Issue by akirabaruah** [cardinalitypuzzles/smallboard#214]
(possible duplicate - @asdfryan might know more)

- Consider what Galactic did and possibly fork implementation
- Also check out discord.js
- Decision: Start the bot in the main smallboard repo

**Comment by asdfryan** [comment]
The other discord features are covered by the other issues, so hijacking this one for the bot.

Features:
- generate list of stuck puzzles
- generate list of unsolved puzzles
- generate list of puzzles for a given tag
- generate number of solves / number of Smallboard entries per meta round

**Comment by rawxfish** [comment]
Something like the Smogon bot would be nice:

![image](https://user-images.githubusercontent.com/1312469/100556626-98babc00-3271-11eb-9d58-e5a67991a0e9.png)
![image](https://user-images.githubusercontent.com/1312469/100556629-9b1d1600-3271-11eb-9933-b463d39288e1.png)
![image](https://user-images.githubusercontent.com/1312469/100556627-99ebe900-3271-11eb-9dde-1e7e8f3e2e95.png)

**Comment by akirabaruah** [comment]
oh yeah that Smogon bot was quite nice - any chance we can reach out to the organizers about it? (maybe that was already done?)

**Comment by rawxfish** [comment]
I looked at the galactic Hypebot (see #discord-bot-spam). It has some useful puzzle commands, but the most interesting commands were ripped out, like the logic puzzle and dropquote solvers :'( 

That bot is implemented as a cog through https://docs.discord.red/en/stable/, which takes care stuff like monitoring commands in Discord, but it seems like hosting it on heroku is sort of a pain (some info here: https://elements.heroku.com/buttons/nntin/red-kun and https://docs.discord.red/en/stable/getting_started.html#hosting)

**Comment by akirabaruah** [comment]
The initial Discord bot is implemented [here](https://github.com/cardinalitypuzzles/smallboard/blob/master/chat/management/commands/rundiscordbot.py), so I'll close this as finished, but feel free to open subsequent feature requests if we're missing any other critical functionality.
