### ISSUE TITLE
Option to hide solved puzzles

### ISSUE THREAD

**Issue by akirabaruah** [cardinalitypuzzles/smallboard#220]
Can start with a simple checkbox at the top of the puzzle list that toggles showing/hiding solved puzzles.

**Comment by rgossiaux** [comment]
Should wait until #251 (react rewrite) before tackling this

**Comment by rgossiaux** [comment]
FYI I left a related comment on #218 which has some overlap with this.

**Comment by rgossiaux** [comment]
Done with #315 , thanks @pcvera !
