### ISSUE TITLE
Increase indenting for sub-puzzles

### ISSUE THREAD

**Issue by akirabaruah** [cardinalitypuzzles/smallboard#221]
Something like this?
```
Meta-Puzzle
    Sub-Puzzle 1
    Sub-Puzzle 2
```

**Comment by akirabaruah** [comment]
@rgossiaux does #237 cover this too?

**Comment by rgossiaux** [comment]
Not specifically but the spacing might be different in the React UI (not aiming for a pixel-identical recreation) and it's just a one-liner to change if we don't like it so not a big deal either way

**Comment by rgossiaux** [comment]
The React UI now has a larger indentation than the old UI + doesn't show expander arrows for all puzzles so I think it's visually much clearer now.
