### ISSUE TITLE
Cleanup UI

### ISSUE THREAD

**Issue by akirabaruah** [cardinalitypuzzles/smallboard#222]
Fix CSS padding, etc. @rgossiaux might have more ideas/context

**Comment by akirabaruah** [comment]
I think @pcvera and @cs-miller had some observations and ideas here as well.

For starters, it might also be good to use a package manager like `npm` or `yarn` to manage javascript and other dependencies.

**Comment by pcvera** [comment]
There are major steps we could take short of resorting to a proper build step that would get us some benefit.

1. exchange `momentjs` for a smaller time library, or maybe drop it entirely. It's 16kb of wire transfer and js parse overhead and is only used in one function, and only in the answer queue page at that.
1. given that our table maxes out at ~150 rows, we don't really need things like pagination or virtualization that our data table dependency is good for. Considering that our current solution somehow actually hurt our performance in the past, I think we could get rid of it for something lighter. I think the one thing the current table may be doing for us well is preserving scroll position, but we can handle that.

If we were to go for a full webpack build, I think the frontend would largely have to be rewritten, the current paradigm doesn't look like it would translate well to packages, but I also don't think a rewrite would be all that difficult.

**Comment by asdfryan** [comment]
The pagination was actually a performance optimization. I recall on  ~200
puzzle loadtests last year, the load times were substantially longer when
we had to render all 200 puzzles in a single page.

**Comment by pcvera** [comment]
How long is "substantially longer"? I'm pretty confident that's a limitation in datatables and not inherent to rendering rows. If we could efficiently display 200+ rows, is it something we'd want to do?

**Comment by rawxfish** [comment]
Last year's messenger chat logs seem to indicate that 176 puzzles took ~5 seconds and 300 puzzles took 20 seconds :'D 

![image](https://user-images.githubusercontent.com/1312469/100658491-26071a80-331d-11eb-8f51-5c9aa8f8e168.png)
![image](https://user-images.githubusercontent.com/1312469/100658660-70889700-331d-11eb-853c-931691510ed9.png)

^ stats were before adding pagination and changes in #114. I don't remember which one ultimately made things faster (probably both?)

I think if we could efficiently display 200+ rows, that would be optimal.

**Comment by pcvera** [comment]
oof, we can _definitely_ beat 20 seconds, #114 suggests it was closer to 5 prior to a change in the loading behavior, but I bet we can beat that too.

**Comment by rgossiaux** [comment]
as a heads up before anyone gets too deep into this, i started prototyping rewriting the main hunt view in React last night. it's going pretty well and i'm hoping it will address the performance issues as well as some other stuff. it's still a work in progress / not production-ready yet but i'm working on [this branch](https://github.com/cardinalitypuzzles/smallboard/tree/rgossiaux/react) if you're curious and i should have more to share in a couple days

**Comment by rgossiaux** [comment]
I'm going to close this since I don't think the discussion is very relevant any more after the switch to React and this issue doesn't track any specific changes. The UI could still stand to be improved a lot but I think we can track it in more specific issues.
