### ISSUE TITLE
Prevent arbitrary pushes to master branch

### ISSUE THREAD

**Issue by akirabaruah** [cardinalitypuzzles/smallboard#226]
Just filing this to make sure we're covered 😄  

@erwa feel free to close if this works already 👍

**Comment by erwa** [comment]
Yup, just disabled direct pushes to master, even for admins, at https://github.com/cardinalitypuzzles/smallboard/settings/branch_protection_rules/12958561

Needed to check
* Require pull request reviews before merging
* Include administrators
