### ISSUE TITLE
Updating puzzle answer should update sheets

### ISSUE THREAD

**Issue by erwa** [cardinalitypuzzles/smallboard#271]
Things we might want to do:

* on adding the correct answer, rename a sheet to include [SOLVED] or the answer in the name
* if we add or delete an answer, we should update the corresponding meta spreadsheets

Probably easiest to do this using a pre or post save hook.

Here's a thread with a bit more context: https://github.com/cardinalitypuzzles/smallboard/pull/257#discussion_r546449433

**Comment by rgossiaux** [comment]
The sheet renaming one is tracked in #135 

I think the spreadsheet updating is already the case-- when @asdfryan ported answer adding to react we made sure to include it.

Gonna close this but lmk if I'm missing something.
