### ISSUE TITLE
Use High Priority/Low Priority tags when ordering puzzles

### ISSUE THREAD

**Issue by rgossiaux** [cardinalitypuzzles/smallboard#289]
High pri puzzles should appear above normal puzzles should appear above low pri puzzles. Should just add this logic to `puzzleComparator` in hunts/src/puzzleSlice.js

**Comment by SamuelJohnson01997** [comment]
Hi @rgossiaux, sounds interesting. I'd like to work on this.

**Comment by rgossiaux** [comment]
@SamuelJohnson01997 At the moment we're only looking for contributions from folks within the puzzle hunt community, sorry.

**Comment by rgossiaux** [comment]
Fixed with #325 , thanks @leonyz !
