### ISSUE TITLE
Implement filtering puzzles by status

### ISSUE THREAD

**Issue by alisonychang** [cardinalitypuzzles/smallboard#34]
For the "All Puzzles" view of a Hunt, the built in Search functionality for Datatable searches on all text associated with the Puzzle object. This means that searching for "Stuck" returns all puzzles regardless of whether their status is "Stuck" or not, because "Stuck" is present in each of their dropdown menus.

I expect filtering the puzzle list by status will be a very common use case during the hunt (e.g., if we want to find all unsolved puzzles), so we should figure out a way to override the Search to only query based on the selected Status - or even add special filtering (checkboxes, if we'd want to see multiple at once, like solving/stuck/pending - aka unsolved?) for the status.

**Comment by asdfryan** [comment]
I'll work on this.

Relevant reading material: 
https://stackoverflow.com/questions/27852497/jquery-datatables-search-within-input-and-select?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

https://datatables.net/reference/api/column().search()

**Comment by asdfryan** [comment]
I fixed the status-search problem -- now it will only search based on the currently selected status. Using the Datatable built-in searching for "pending" or "solved" will correctly yield puzzles with matching statuses.

Is this sufficient? Or do we also want column-level search/filtering. It's doable but I worry it will clutter the UI.

**Comment by erwa** [comment]
I like the idea of column-level search/filtering. I think it will be useful for the Tags, Puzzle, Answer, and Status fields. You could put the column search/filter box at the bottom of the columns to make it less clutter-y in the UI.

**Comment by asdfryan** [comment]
Sounds good -- I actually prototyped exactly what you said yesterday and then changed my mind.
