### ISSUE TITLE
[bot] Implement paging for long responses

### ISSUE THREAD

**Issue by akirabaruah** [cardinalitypuzzles/smallboard#352]
When returning long lists of puzzles, we hit the 1024 character limit. We can get around this by implementing some sort of paging scheme where we list N puzzles only, with an option to list more in a subsequent command.

**Comment by akirabaruah** [comment]
We currently just send multiple response all at once to get around the 1024 character limit. I think that should sufficiently cover this issue. Thoughts?

**Comment by rgossiaux** [comment]
Seems good to me mostly although we might not even want people to be able
to list every puzzle at once. Feels like we should try to provide commands
that are going to return a smaller # of results (eg list unsolved puzzles
vs list all puzzles). But yeah multiple messages seems simple and good.
