### ISSUE TITLE
Make editing of puzzle status consistent

### ISSUE THREAD

**Issue by alisonychang** [cardinalitypuzzles/smallboard#36]
Currently, anyone can change a puzzle's status from the "all puzzles" UI, but once it's in "pending" or "solved" status, it gets disabled, and only admins can change it further. This can cause confusion e.g., in case of accidental status changes.

To avoid getting into a stuck status state (lol) by accident, we should either have:
1) Only the phone person can edit status of puzzles. If they mark something as solved but then need to edit it, that's fine.
2) No restrictions on puzzle status editing. This means after a puzzle is marked as solved, anyone can change the status again as needed.

**Comment by erwa** [comment]
Hmm, here's my take:

* I think general users should only need to set SOLVING (default) and STUCK.
* PENDING shouldn't be an option but should be set automatically when a guess is submitted
* SOLVED also shouldn't be an option but should be set automatically when the phone person selects CORRECT.

If CORRECT or INCORRECT is set incorrectly, it can be edited from the "Answer Queue" page.

**Comment by asdfryan** [comment]
+1 to everything Anthony said.

I think this just means that the UI should reflect this by only allowing users to select from SOLVING and STUCK.
