### ISSUE TITLE
"Unsolved" and "Priority" filters are unclear

### ISSUE THREAD

**Issue by asdfryan** [cardinalitypuzzles/smallboard#362]

**Comment by asdfryan** [comment]
Potentially controversial opinion: We should get rid of `Unsolved`, and rename current `Priority` to `Unsolved`.

It feels weird to click on `Unsolved` and see Solved puzzles. After discussing offline, we agree that `Priority` is the more useful view -- so we should keep that one.

**Comment by rgossiaux** [comment]
Fixed by #363 , thanks @pcvera !
