### ISSUE TITLE
Discord channels should not be created unless puzzle is successfully created

### ISSUE THREAD

**Issue by asdfryan** [cardinalitypuzzles/smallboard#397]
During the playtest, there were many "dangling channels" because we first create the channels, and then the puzzle -- the latter can fail (due to invalid URL, same name, etc.).

We should move channel creation to post_save upon puzzle creation.

**Comment by asdfryan** [comment]
Marked as critical, as this bug is easy to reproduce and will likely occur in Mystery Hunt especially if a bunch of people try to create the same puzzle at the same time. Currently, each attempt will create a voice channel + text channel that won't be GC'ed.

**Comment by rgossiaux** [comment]
I think my PR #396 fixes this incidentally. I've been trying to move things
generally into transaction.on_commit blocks which can prevent this kind of
issue.

**Comment by asdfryan** [comment]
Very nice! Glad to have one fewer task on my plate. :)

**Comment by asdfryan** [comment]
Fixed by #396
