### ISSUE TITLE
Celery tasks should not be stored in DB

### ISSUE THREAD

**Issue by asdfryan** [cardinalitypuzzles/smallboard#472]
There are O(5k) celery tasks in our DB:
![image](https://user-images.githubusercontent.com/1498449/111888351-f72eb600-8998-11eb-8891-2f1d6da49cd3.png)

I got an email from Heroku:

_The database DATABASE_URL on Heroku app smallboard is approaching its allocated storage capacity.The database contains 7,672 rows. The Hobby-dev plan allows a maximum of 10,000 rows. If the databases exceeds 10,000 rows then INSERT privileges will be revoked, preventing more data from being written. INSERT privileges are automatically reinstated if rows are removed and the database once again complies with the plan limit.To avoid a disruption to your service, migrate the database to a Basic ($9/month) or higher plan:https://hello.heroku.com/upgrade-heroku-postgres#upgrading-with-pg-copy_

_If you are unable to upgrade the database, you should limit or reduce the number of records in it._

We could just pay $9 a month, but I'm fairly certain that we don't need these in our DB.

As Akira alluded to, we should just have Redis manage these instead of storing them in our DB.

**Comment by akirabaruah** [comment]
Current config for Celery task results: https://github.com/cardinalitypuzzles/smallboard/blob/c50478e3bf7dce9747fcf71123cd4623102ca11e/smallboard/settings.py#L284

See https://docs.celeryproject.org/en/v2.3.3/tutorials/otherqueues.html#configuration for switching to Redis.
