### ISSUE TITLE
Multi-tenancy: smallboard should support per-hunt settings to allow multiple teams to use the same smallboard instance simultaneously

### ISSUE THREAD

**Issue by erwa** [cardinalitypuzzles/smallboard#501]
Currently any user who can login to a smallboard instance can see all the created hunt instances.

It would be nice if several different teams could use the same smallboard instance for the same and/or different hunts simultaneously, where each team creates its own hunt instance specifying its own Google Drive folder, team members who have access, Sheets template file, Discord server, etc.

**Comment by rgossiaux** [comment]
Duplicate of #191

**Comment by erwa** [comment]
Ah thanks. I was looking for a duplicate issue but couldn't find that one.
