### ISSUE TITLE
Ability to group puzzles in rounds

### ISSUE THREAD

**Issue by erwa** [cardinalitypuzzles/smallboard#6]
Puzzle hunts usually have multiple rounds (each with a meta). We should be able to group puzzles into rounds in addition to listing all puzzles. See Codex Blackboard for an example of this: https://www.youtube.com/watch?v=oHMN3GujuzQ

**Comment by alisonychang** [comment]
This would also handle a case like Mystery Hunt 2019 where there were various towns, each of which had a number of puzzles. https://www.mit.edu/~puzzle/2019/

**Comment by erwa** [comment]
This could also be handled using tags (#32).

**Comment by asdfryan** [comment]
As discussed in messenger, we should:

- Keep meta as a separate field from generic tags
- Make the meta field searchable and orderable
- Disallow self-assignment for metas (the meta for a metapuzzle can't be itself) both in UI and in the model
- Have the "META" text in the puzzle name perform a filter
- Have the puzzle table have some sort of intelligent sorting grouped by metas upon initial display

**Comment by asdfryan** [comment]
I think we should:
* Disallow sorting by users on any column (if they want to look for a particular puzzle, we have filter/search support)
* Presort the puzzles intelligently

I propose that the intelligent sort should sort in the following way:
MetaMeta1 (Unsolved)
- Meta1 (Unsolved)
-- Puzzle1 (Unsolved)
-- Puzzle2 (Solved)
-- Puzzle3 (Solved)
- Meta2 (Solved)
-- Puzzle4 (Unsolved)
-- Puzzle5 (Solved -- hidden)
-- Puzzle6 (Solved -- hidden)
MetaMeta2 (Solved)
- Meta4 (Unsolved)
-- Puzzle7 (Solved)
-- Puzzle8 (Unsolved)
- Meta5 (Solved -- hidden)
-- Puzzle9 (hidden)
-- Puzzle10 (hidden)

**Comment by erwa** [comment]
I like the idea of presorting the puzzles intelligently (e.g.: grouping by meta). What about puzzles that haven't been assigned to any meta yet? How do you think they should be sorted?

I think we need some notion of "round" (which, in last year's hunt, might correspond to a "town"). Otherwise the list of puzzles might get a bit too messy. I think it'd be nice to have some grouping by "round" and be able to search/filter/sort within each round. Here's an example of "Rounds" from Codex Blackboard:

![rounds](https://user-images.githubusercontent.com/544734/70563438-3e09eb00-1b5c-11ea-8fa5-d0c5a795f181.png)

(screenshot from https://www.youtube.com/watch?v=oHMN3GujuzQ)

I think a "New Round" button and have a separate table of puzzles per round would be useful.
