### ISSUE TITLE
"Puzzle not created because the form was invalid." doesn't explain why the form was invalid

### ISSUE THREAD

**Issue by maximized** [cardinalitypuzzles/smallboard#66]
I think it was invalid because I included a URL that wasn't valid.

**Comment by erwa** [comment]
Ah, yes, I can repro this easily. Thanks for reporting.

**Comment by rgossiaux** [comment]
Going to take the assignment for this one since the errors have changed with the new API.

**Comment by rgossiaux** [comment]
This error doesn't exist any more in the React UI. The API returns more descriptive error messages when adding a puzzle so I don't think this is an issue.
