### ISSUE TITLE
Can't create puzzle without URL

### ISSUE THREAD

**Issue by maximized** [cardinalitypuzzles/smallboard#67]
Situations in which this might be necessary
1. Hidden puzzle
2. Known meta but not yet unlocked
3. Physical puzzle (although there will probably still be a page you could link to)
4. Left Out does something weird where there is a ClueKeeper hunt within Mystery Hunt

**Comment by asdfryan** [comment]
+1 I think this is important.

We should also consider making URL a non-unique field now that we have edit/delete support.
