### ISSUE TITLE
Reserve Some Tag Colors for Top Tier Tags

### ISSUE THREAD

**Issue by maximized** [cardinalitypuzzles/smallboard#69]
Red, green, yellow for High Priority, Backsolved, and Low Priority. Other tags shouldn't be able to use these colors.

**Comment by rawxfish** [comment]
Should black be reserved for tags associated with metas?

**Comment by maximized** [comment]
Sure. I hope most user-made tags are one color. There should be a few during the hunt that we want to draw attention to by changing color, but not the norm.

**Comment by erwa** [comment]
@rawxfish, @maximized: is this considered fixed now?

**Comment by rawxfish** [comment]
yeah I think so
