### ISSUE TITLE
Table UI changes on initial load

### ISSUE THREAD

**Issue by erwa** [cardinalitypuzzles/smallboard#78]
When visiting the hunts/X page, you'll initially see a dense listing of puzzles, and then once the JavaScript has finished processing, the layout will change suddenly:

Initial:
![initial](https://user-images.githubusercontent.com/544734/70869387-64fb5f00-1f58-11ea-90f1-87784e232a4d.png)

Final:
![final](https://user-images.githubusercontent.com/544734/70869388-64fb5f00-1f58-11ea-9b3d-13d787dd752c.png)

This is a little jarring and would be nice to fix.

**Comment by asdfryan** [comment]
The time difference between Initial and Final is the amount of time it takes for our javascript code to run -- which is pretty slow.

We need to do something about our javascript performance. Based on a few tests I've run, most of it is (I think) datatable overhead, but I'm not entirely sure.

**Comment by erwa** [comment]
Related: #82

**Comment by erwa** [comment]
Evidence that suggests bulk of loading time is transferring HTML data from server to client:

Most of the HTML is for modals we show when buttons and icons are clicked. With modals, here's the load time:
![transfer-modals](https://user-images.githubusercontent.com/544734/70875559-575bce80-1f84-11ea-930e-ca40263bf552.png)

With the modal code deleted, here is the load time:
![transfer-no-modals](https://user-images.githubusercontent.com/544734/70875597-6d698f00-1f84-11ea-9c5e-2264d418378d.png)

One idea is instead of pre-generating the modal HTML code server-side, we generate it client it via JavaScript when the buttons and icons are clicked.

**Comment by erwa** [comment]
@lilyzhou we made some performance optimizations including adding paging to the puzzle table. I think the UI layout no longer changes after the initial load (because we now render everything using JavaScript on the client). Can you check https://smallboard.herokuapp.com/hunts/1/ and see if it looks ok to you now?
