### ISSUE TITLE
Ability to make announcement across Small Board

### ISSUE THREAD

**Issue by erwa** [cardinalitypuzzles/smallboard#9]
We should have an admin feature that allows us to post, say, a banner announcement across all Small Board pages. Using a Slack #announcements channel might also be sufficient.

**Comment by asdfryan** [comment]
We have an #announcements channel that only the admin (Cardinality Puzzles) can post to. All correct answers are automatically announced on that channel as of now. If that's too much / too little, we can adjust it as necessary.

I don't see much of a need to add a free-form announcement feature on the webapp.
